name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        julia-version: ["1.6", "1.8", "nightly"]
        julia-arch: [x64]
        include:
          - name: Linux 32-bit
            os: ubuntu-20.04
            julia-version: "1.6"
            julia-arch: x86
          # This fails with "A dynamic link library (DLL) initialization routine failed."
          # - name: Windows 32-bit
          #   os: windows-2019
          #   julia-version: "1.6"
          #   julia-arch: x86
          - name: Windows 64-bit
            os: windows-2019
            julia-version: "1.6"
            julia-arch: x64
          - os: macos-11
            julia-version: "1.6"
            julia-arch: x64
    steps:
      - uses: actions/checkout@v3
      - name: setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: build package
        run: julia --check-bounds=yes --inline=no --project -e 'using Pkg; Pkg.build("Chemfiles")'
      - name: run tests
        run: julia --check-bounds=yes --inline=no --project -e 'using Pkg; Pkg.test("Chemfiles"; coverage=true)'
      - name: run extra checks
        if: matrix.os == 'ubuntu-20.04'
        run: ./scripts/check_used_functions.py
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-20.04'
        with:
          fail_ci_if_error: true
          verbose: true
